package com.rfc.util;

public interface Constants {
String XL_ATTENDANCE_HEADING="COMPLETE ATTENDANCE";
String XL_ATTENDANCE_COLUMN_HEADING_DATE="DATE";
String XL_ATTENDANCE_COLUMN_HEADING_NAME="NAME";
String XL_ATTENDANCE_COLUMN_HEADING_TOTAL="TOTAL";
String XL_ATTENDANCE_COLUMN_HEADING_ATTENDANCE="ATTENDANCE";
String XL_ATTENDANCE_COLUMN_PRESENT="P";
String XL_ATTENDANCE_COLUMN_ABSENT="A";
}
